/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsReconnect = {
  reconnectSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebarsReconnect;
